# Generated by Django 4.0.6 on 2022-07-23 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_post_category_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='account',
            name='bio',
        ),
    ]
