# Generated by Django 4.0.6 on 2022-07-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile-img/profile_pic.png', max_length=255, null=True, upload_to=''),
        ),
    ]
