# Generated by Django 4.0.6 on 2022-07-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_comment_email_alter_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profile_image',
            field=models.ImageField(default='/profile-img/profile_pic.png', upload_to=''),
        ),
    ]
