# Generated by Django 4.0.6 on 2023-10-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_tag_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'Newsletter Email'},
        ),
        migrations.AddField(
            model_name='account',
            name='github',
            field=models.URLField(blank=True, max_length=250, verbose_name='GitHub URL'),
        ),
        migrations.AddField(
            model_name='account',
            name='linkedin',
            field=models.URLField(blank=True, max_length=250, verbose_name='LinkedIn URL'),
        ),
        migrations.AddField(
            model_name='account',
            name='twitter',
            field=models.URLField(blank=True, max_length=250, verbose_name='GitHub URL'),
        ),
    ]
