# Generated by Django 4.0.6 on 2023-10-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_category_options_alter_newsletter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='twitter',
            field=models.URLField(blank=True, max_length=250, verbose_name='Twitter URL'),
        ),
    ]
